### ISSUE TITLE
MAX_SLICE_GAP appears to be documented as 'number of points' but implemented as 'number of bytes'

### ISSUE THREAD

**Issue by ciaranj** [graphite-project/ceres#17]
The current default of 80 translates in the code 80 bytes (i.e. 10 data points).  Is this the intended meaning of this setting as I've read in other parts of google ( e.g. https://github.com/graphite-project/carbon/pull/116/files ) that the constant specifies the number of datapoints, which in terms of the ceres.py implementation would actually be required as being set to 640 to  skip 80 datapoints.

**Comment by deniszh** [comment]
https://github.com/dkulikovsky/ceres/commit/0ebebf3db5d4da45e4359629191be9348722398c should be ported here

**Comment by iain-buclaw-sociomantic** [comment]
This was fixed in 0d287b06471c7716870fa7f02b00a36905e658ec
