### ISSUE TITLE
Compatibility with graphite-api

### ISSUE THREAD

**Issue by Civil** [graphite-project/ceres#22]
Right now ceres won't work with graphite-api out of box. It requires https://github.com/vladimir-smirnov-sociomantic/ceres/commit/9873d0b31188c5329cb5ae89408a0e8f12e6ad5c this to be picked-up.

**Comment by ibuclaw** [comment]
I thought it best to fix graphite-api instead: https://github.com/brutasse/graphite-api/commit/8b12322125a8800bca28a1ec8f9803e96e92224f
