### ISSUE TITLE
It's more sane to read until previous point, than until latest one

### ISSUE THREAD

**Issue by Civil** [graphite-project/ceres#23]
https://github.com/vladimir-smirnov-sociomantic/ceres/commit/3ec9d5fbd3c75ff9f35134cb88e0259b1dafb927

Use-case for that - when you have a metric with low precision (3600s or higher) if you ask graphite for the data that doesn't align with retention period (e.x. until current type) ceres will return "None" point with timestamp in future, which is wrong - it's better not to show one last point, than to show future data.

**Comment by iain-buclaw-sociomantic** [comment]
Note, this is also the behaviour of Whisper.

https://github.com/graphite-project/whisper/blob/91bf925970e43563e3e407e8b33485512f3d7772/whisper.py#L879-L883

**Comment by iain-buclaw-sociomantic** [comment]
@deniszh - In any case, it seems this was applied in #30, so close? :-)

**Comment by deniszh** [comment]
Yep, I think we can close this.
