### ISSUE TITLE
Recalculate series can produce broken output in rare cases

### ISSUE THREAD

**Issue by Civil** [graphite-project/ceres#24]
https://github.com/vladimir-smirnov-sociomantic/ceres/commit/7e06290f771c197c7c549091db076ec354e58d44

Sorry, I don't have test case for that, but it was related to rollup process. From time to time, recalculate series, that's written like this, produces bad results.

Also, reduce and lambda is worse in terms of performance, if you'll use pypy as a main interpreter.

**Comment by iain-buclaw-sociomantic** [comment]
This can be closed as it does not really apply to Ceres (anymore).
